# Generated by Django 5.0.2 on 2024-02-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
