# Generated by Django 5.0.2 on 2024-02-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artchers', '0002_vote_isconfirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='image',
            field=models.FileField(upload_to='district_src'),
        ),
        migrations.AlterField(
            model_name='district',
            name='image_el',
            field=models.FileField(upload_to='district_src'),
        ),
    ]
