# Generated by Django 5.0.2 on 2024-02-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artchers', '0003_alter_district_image_alter_district_image_el'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='district',
            name='image_el',
            field=models.FileField(upload_to='images'),
        ),
    ]
