# Generated by Django 4.2.10 on 2024-02-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artchers', '0004_alter_district_image_alter_district_image_el'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_time_code', models.CharField(max_length=20)),
            ],
        ),
    ]
