# Generated by Django 4.2.10 on 2024-02-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artchers', '0005_onetimelinkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='key',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
