# Generated by Django 4.2.10 on 2024-02-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artchers', '0006_vote_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='key',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
