# Generated by Django 4.2.10 on 2024-03-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artchers', '0007_alter_vote_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=200)),
                ('score', models.BigIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
