# Generated by Django 5.0.3 on 2024-03-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artchers', '0008_pacman'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='composition',
            field=models.CharField(default='zezaez', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='description',
            field=models.TextField(default='zezezez', max_length=3000),
            preserve_default=False,
        ),
    ]
