# Generated by Django 5.0.3 on 2024-03-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artchers', '0009_district_composition_district_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=400)),
                ('date', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('image', models.FileField(upload_to='images')),
            ],
        ),
    ]
