# Generated by Django 5.0.3 on 2024-03-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artchers', '0011_event_isshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district1', models.IntegerField()),
                ('district2', models.IntegerField()),
                ('district3', models.IntegerField()),
                ('district4', models.IntegerField()),
                ('district5', models.IntegerField()),
                ('district6', models.IntegerField()),
            ],
        ),
    ]
